[package]
name = "services"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = { version = "2.3.2", features = ["hyper-client"] }
serde = { version = "1.0.195", features = ["derive"] }
