//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "event_status")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub gameweek: i32,
    pub deadline_time: DateTimeWithTimeZone,
    pub finished: bool,
    pub data_checked: bool,
    pub average_entry_score: i32,
    pub highest_scoring_entry: i32,
    pub deadline_time_epoch: i32,
    pub is_previous: bool,
    pub is_current: bool,
    pub is_next: bool,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
