//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::event_status::Entity as EventStatus;
pub use super::match_result::Entity as MatchResult;
pub use super::r#match::Entity as Match;
pub use super::user::Entity as User;
