//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "chip_rule")]
pub enum ChipRule {
    #[sea_orm(string_value = "All")]
    All,
    #[sea_orm(string_value = "AnyChip")]
    AnyChip,
    #[sea_orm(string_value = "NoChip")]
    NoChip,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "match_status")]
pub enum MatchStatus {
    #[sea_orm(string_value = "Finished")]
    Finished,
    #[sea_orm(string_value = "Live")]
    Live,
    #[sea_orm(string_value = "Next")]
    Next,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "transaction_flag")]
pub enum TransactionFlag {
    #[sea_orm(string_value = "Down")]
    Down,
    #[sea_orm(string_value = "Up")]
    Up,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "transaction_type")]
pub enum TransactionType {
    #[sea_orm(string_value = "CreateMatch")]
    CreateMatch,
    #[sea_orm(string_value = "Event")]
    Event,
    #[sea_orm(string_value = "Purchase")]
    Purchase,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "transfer_rule")]
pub enum TransferRule {
    #[sea_orm(string_value = "Limit0")]
    Limit0,
    #[sea_orm(string_value = "Limit1")]
    Limit1,
    #[sea_orm(string_value = "Limit2")]
    Limit2,
    #[sea_orm(string_value = "Limit3")]
    Limit3,
    #[sea_orm(string_value = "Limit4")]
    Limit4,
    #[sea_orm(string_value = "NoLimit")]
    NoLimit,
}
